### ISSUE TITLE
[BUG]: Username entered before fully Typed

### ISSUE THREAD

**Issue by TillDV** [maurodesouza/profile-readme-generator#33]
### What happens?

My Username is TillDV but it already automatically enters at TillD and I can't change it unless I change the value in the browser's local storage.

### What are the steps to reproduce this issue?

Just type in the name

### What were you expecting to happen?

The Username enters before complete

### Additional information about your environment

- **Device**: Macbook M1 
- **OS**: MacOS
- **Browser**: Safari

**Comment by maurodesouza** [comment]
Thanks @TillDV ❤
