### ISSUE TITLE
[BUG]: Adding C++ as a skill 

### ISSUE THREAD

**Issue by vigneshsaravanakumar404** [maurodesouza/profile-readme-generator#36]
### What happens?

When I searched for C++ to add to the language section of template #2 I get "Application error: a client-side exception has occurred (see the browser console for more information)".

### What are the steps to reproduce this issue?

Click template #2
Enter your github profile in the 2 sections
try adding C++ as a langauge 

### What were you expecting to happen?

I was expecting to be able to add c++ as a langauge

### Additional information about your environment

- **Device**: HP pavilion 
- **OS**: Windows 11
- **Browser**: Edge
- **Version**: idk

**Comment by maurodesouza** [comment]
Thanks @vigneshsaravanakumar404 ❤

Regarding your search, currently only [Devicons](https://devicon.dev) icons are supported, and `C++` is referred to as `cplusplus`. I am already working to support aliases and other icon providers, such as [Simple Icons](https://simpleicons.org) and [Skill Icons](https://skillicons.dev).

However, currently, to find `C++`, you need to search for `cplusplus`, to find `C#`, you need to search for `csharp`.
