### ISSUE TITLE
[BUG]: Small typo in the headline template

### ISSUE THREAD

**Issue by CassioLeodegario** [maurodesouza/profile-readme-generator#4]
### What happens?

When creating a new readme using the template 2 the readline comes with an small incorrect character case
Hi 👋! My name is ... and **i'm** a ..., from ....
when it should be 
Hi 👋! My name is ... and **I'm** a ..., from ....

### What are the steps to reproduce this issue?

1 - Create a new Readme
2 - Select template 2
3 - Edit the headline text

### What were you expecting to happen?

It should show Hi 👋! My name is ... and **I'm** a ..., from ....

### Additional information about your environment

- **Device**: Desktop
- **OS**: Windows
- **Browser**: Brave
- **Version**: V1.39.122

**Comment by maurodesouza** [comment]
Resolved in #7
