### ISSUE TITLE
[FEATURE]: Copy to Copied!

### ISSUE THREAD

**Issue by PraptiSawant** [maurodesouza/profile-readme-generator#42]
### What would you like to be added/improved?

The text of the tooltip should change from "**Copy**" to "**Copied !"** after copying the readme.

### Describe the solution you'd like

The text of the tooltip should change from "**Copy**" to "**Copied !"** after copying the readme.
Changing this would help user understand that the text is copied as of now it only stays copy making it difficult to understand.
I have worked on the solution of the problem.

**Comment by balogun14** [comment]
@PraptiSawant can you explain this issue a bit more i would love to work on this
