### ISSUE TITLE
[BUG]: snake feature not working 

### ISSUE THREAD

**Issue by basavarajakj** [maurodesouza/profile-readme-generator#50]
### What happens?

After adding github username to get snake feature nothing is showing in result page

### What are the steps to reproduce this issue?

1. Go to home page
2. Click snake tab
3. Give github username
4. click generate Readme

### What were you expecting to happen?

I want code for that feature

### Additional information about your environment

- **Device**: desktop
- **OS**:  windows
- **Browser**:  chrome(brave)
- **Version**: 1.58.131

**Comment by lucas-fsousa** [comment]
I also had problems trying to generate the snake animation!

**Comment by maurodesouza** [comment]
Hi @basavarajakj and @lucas-fsousa  👋

I tried to reproduce the issue, but it's apparently working here. Can you provide a video/gif to give more context about the problem? Thanks!

**Comment by basavarajakj** [comment]
Hey @maurodesouza Know its working fine but how to customize this snake animation in local profile. Is there any documentation

**Comment by No898** [comment]
Hello! 

can someone recommend me what am i doing wrong? 

i trying 

![image](https://github.com/maurodesouza/profile-readme-generator/assets/82420070/2056b0c2-097c-4c0f-952f-66b5457f2b96)
`name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: No898
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
`

i am trying to use action to generate snake (never used action before)

**Comment by lucas-fsousa** [comment]
@No898 I had exactly this error.

**Comment by No898** [comment]
@maurodesouza can you help us to solve it? thank you for your work

**Comment by maurodesouza** [comment]
Hi there 👋

I pushed an update related to the snake.yml animation to comply with the [snk](https://github.com/Platane/Platane/blob/master/.github/workflows/main.yml) feature recommended settings.

It should work properly now. Please inform me if it is still not working.

Thanks ❤
