### ISSUE TITLE
[BUG]: Error when generating music template (Recently)

### ISSUE THREAD

**Issue by davidfer1112** [maurodesouza/profile-readme-generator#51]
### What happens?

You can't see the recent songs, i.e. even in the preview you can't see the list of songs (linked image). 

![Error](https://github.com/maurodesouza/profile-readme-generator/assets/90224781/9e62cd0c-6e29-486b-85f4-bdee26e8b307)

### What are the steps to reproduce this issue?

1. Go to music
2. Select the Recently type
3. enter user

### What were you expecting to happen?

What is supposed to happen is that it will show the list of recent songs, according to user

### Additional information about your environment

- **Device**: desktop
- **OS**:  MacOS
- **Browser**: chrome
- **Version**: 10.15 

### Additional context

The error occurs, as the API is not being used correctly, suddenly this was updated leaving the version being implemented obsolete, this is the way it is currently being used:

    <div align="center">
      <a href="https://open.spotify.com/user/{userName}">
        <img src="https://spotify-recently-played-readme.vercel.app/api?count=5" alt="Spotify recently played"  />
      </a>
    </div>
    
    
But the current and proper way to use the API is this:

    <div align="center">
      <a href="https://open.spotify.com/user/{userName}">
        <img src="https://spotify-recently-played-readme.vercel.app/api?user={userName}&unique={true|1|on|yes}"  />
      </a>
    </div>

Where it says {userName} replace with your username, also remember to use the user provided by the Spotify API when giving authorization, at the top it says "Authenticated as {userName}".

API authorization link: https://spotify-recently-played-readme.vercel.app

**Comment by maurodesouza** [comment]
Hi @davidfer1112, thanks for report ❤️
