### ISSUE TITLE
[BUG]: request error

### ISSUE THREAD

**Issue by maurodesouza** [maurodesouza/profile-readme-generator#54]
### What happens?

On entry in the main page or on generating the readme in the network, it's possible to see a pending request; after a few seconds, it gets the error 504 Gateway Timeout.

### What are the steps to reproduce this issue?

1. Open your console on the network tab;
2. Go to the main page or generate a readme;

### What were you expecting to happen?

I expect that there are no errors in the API.

### Additional information about your environment

- Device: desktop
- OS: windows
- Browser: opera
- Version: 95.0.4635.46

**Comment by ElryWeeb** [comment]
why is this closed if its still an issue ? Even on my own instance i still get that error, so its not an Ratelimit.
![image](https://github.com/maurodesouza/profile-readme-generator/assets/144011449/584e2df4-f555-4112-bd4d-baa4e905dcd5)

**Comment by maurodesouza** [comment]
Hi @ElryWeeb 👋

That issue is related to a counter API I used to see how many readmes were generated and the number of page visits. You can see more details in the PR #55 

Regarding issues related to the features that this project uses, I don't have control over them. I just use them. So, if you have any problem with the related feature, it is better to go to the feature project and ask for help there.

I intend to create a page or add links to the features to make it easier to find their github repos.
