### ISSUE TITLE
[BUG]: snake don't work

### ISSUE THREAD

**Issue by venelouis** [maurodesouza/profile-readme-generator#67]
### What happens?

Snake don't work

### What are the steps to reproduce this issue?

After I click the button "generate README" at website the snake related code don't work:
<img src="https://raw.githubusercontent.com/venelouis/venelouis/output/snake.svg" alt="Snake animation" />

### What were you expecting to happen?

snake work

### Additional information about your environment

github

### Additional context

I don't know if it helps but the code is this:
<img src="https://raw.githubusercontent.com/venelouis/venelouis/output/snake.svg" alt="Snake animation" />

**Comment by haupt-pascal** [comment]
Cheers! Did you tried to open the GitHub Actions tab in your profile, click on the Generate snake animation (left sidebar) and run the workflow? You need to add the github workflow as well to create the snake.

**Comment by venelouis** [comment]
I don't know how to do it, I dont see this option to "click": "Generate snake animation"

I dont know how to run a workflow, i am new, I am still learning
![githubactions](https://github.com/maurodesouza/profile-readme-generator/assets/37526748/61614d14-4290-4d78-b255-0f48ad53cea6)

I have tried other options, but the snake just got stoped, so I just commented the snake code, as you can see in my profile.

**Comment by venelouis** [comment]
* but i am in the middle of github foundadtions certification studies by microsoft learn, the next is is github actions... https://resources.github.com/learn/certifications/ so I will study more...

**Comment by haupt-pascal** [comment]
Have you even creates the .github/workflow/snake.yml you had to create? It is shown up when youve clicked generate readme above the readme

**Comment by venelouis** [comment]
oh I see now, i just copied the readme.md thanks!
