### ISSUE TITLE
[BUG]: Snake animation Error 

### ISSUE THREAD

**Issue by AjayKusekar** [maurodesouza/profile-readme-generator#71]
### What happens?

The Snake animation is not working

### What are the steps to reproduce this issue?

Go to your Animation componenet and please fix this

### What were you expecting to happen?

i am expecting to run the animation in my readme file, its not working

### Additional information about your environment

- **Device**: [Laptop]
- **OS**: [ windows]
- **Browser**: [chrome]

**Comment by Martimex** [comment]
I think you forgot to run the Github Action to execute the snake animation. Here is how you can do it :  
1. Go to the "Actions" tab in your README repository 
2. Click the "Configure" button in the Simple workflow section 
3. Now you should see a file editor. **Inside here you should leave only the contents of snake.yml file**, which you should get as one of output files after clicking "Generate README" inside Profile Readme Generator app. Also, rename this file to snake.yml and then press "Commit changes..." 
4. Visit "Actions" tab again and there you should see a new Workflow - Generate snake animation. Click on it and then press "Run workflow" button. After couple of seconds, you should have Snake Animation up and running.

Please let me know if above steps worked for you.

**Comment by Ash-ura** [comment]
Also facing the same issue. Followed your instructions and still did not see any change. I see that the output branch is created and the snake.svg is being pushed there but outside of that, the snake animation shows as a broken link.

github_user_name: ${{ github.repository_owner }}

Is this parameter supposed to be edited with our github username?

**Comment by Ash-ura** [comment]
> Also facing the same issue. Followed your instructions and still did not see any change. I see that the output branch is created and the snake.svg is being pushed there but outside of that, the snake animation shows as a broken link.
> 
> github_user_name: ${{ github.repository_owner }}
> 
> Is this parameter supposed to be edited with our github username?

FIxed it, the generated link pointing to my repository was incorrect. Thanks

**Comment by Martimex** [comment]
You are welcome. Glad you found it helpful !

For those, who might be wondering in the future : 

> github_user_name: ${{ github.repository_owner }}
> 
> Is this parameter supposed to be edited with our github username?

You should not edit this inside the generated ``snake.yml`` file.  Simply copy and paste all the code, like I mentioned in the step 3.

**Comment by AjayKusekar** [comment]
Thanks I got it
