### ISSUE TITLE
[BUG]: There is a bug with logo on the web application.

### ISSUE THREAD

**Issue by alexbud1** [maurodesouza/profile-readme-generator#9]
### What happens?

When you're scrolling bunch of skills to choose, logo of Django does not display properly. So users can see only alternative text. The same issue is, when you try to choose variant of Django logo.

### What are the steps to reproduce this issue?

1. open website [](https://profile-readme-generator.com/)
2. Scroll to find Django logo.

### What were you expecting to happen?

I expected to see proper Django logo instead of alt text.

### Additional information about your environment

- **Device**: [laptop]
- **OS**: [Linux Manjaro]
- **Browser**: [chrome]

**Comment by maurodesouza** [comment]
Thanks @alexbud1 ❤
